#!/usr/bin/env bash
set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"

# IMPORTS #
source "$SCRIPT_DIR/src/version.sh"
source "$SCRIPT_DIR/src/ui.sh"
source "$SCRIPT_DIR/src/config.sh"
source "$SCRIPT_DIR/src/tailnet.sh"
source "$SCRIPT_DIR/src/env.sh"
source "$SCRIPT_DIR/src/branches.sh"
source "$SCRIPT_DIR/src/deploy.sh"



